language: node_js
node_js: node
os: linux
sudo: false
cache:
  yarn: true
matrix:
  fast_finish: true
script: run-s test build-html
after_success: test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "source" && bash tools/deploy.sh
notifications:
  email: false
  slack:
    secure: kWuOR9YLV9FRX8wkr/pIvrdLzEcmUG7WYnqkS13T26+o+XyVa3E1ESqmOgCYMU9D0+5jjweRSNRVk7YCKcAwgcMFvwbbMgxVmmPeAOzVant9B1kv8HzdXE7Gd5eipItSxEELYa8ufhVOu5nY/vbCgyr/soPIKbRcDqf3QEXj0a7iWt57bPaRwN/13y1DOy0E1DJuVu4a4oVfsCerVWGYeJafFg7xVVZnvKLS0pqF5zrYuUzvO2hrnGdKz4CvRZym20XDAvhfmG4udcgld2mrxcDF6hJpM3bGDew91/ns+hEyLev44G76Z8XsI/em9d0FQfe27zdzIfaTOWUKY72fbgrJX+YU+HjS5MHRzgZE79nS8b+91VM1EazGPeHsy93ihdXoqkQ0vHHZgxzpjbTBXmLUgRCk3Vb5tc5wspEWTjOi2X7UAUQG3n9iiy7vMfu+/4HUgG8kL97MjmZaNSYTcfv0UDvU8nssRyD/rqMD/Vy6ZXhU/O0Hn47A6a2sgcXXw4neJwwDAC4hKBY89WeCYU6YQU+CnKuc7kHcDmjHBvbV+gXRBQitC5ew3ZZhloDBJYkD52MMOrsgxj+gt6JypKXdX0kXNnXt2HfsbazX/EJMSEL4XMLsmDWzho
